#-------------------------------
# General Site Settings
title: tôi làm BA
logo: /favicon/logoyellow@2x.png # You can add own logo.
description: Share business analyst skill to others.


#-------------------------------
# Author Settings
author:
  name: Hoàng Phan
  image: 01.jpg
  say-hello: Hello, Mình là <strong>Hoàng Phan</strong>
  bio: Là một IT Business Analyst, chia sẻ đến bạn đọc kinh nghiệm bản thân về <strong>Business Analyst</strong>, <strong>Testing</strong>, <strong>Dev</strong>, and <strong>Cuộc sống</strong>. Mình cũng yêu thích <a href="https://soundcloud.com/minh-hoang-phan-61265012/trai-tim-ben-le-harmonica-tone-a/">harmonica</a> và guitar.


#-------------------------------
# Contact links
facebook: https://facebook.com/hoangpm96 # Add your Facebook handle
instagram: https://instagram.com/hoangpm96 # Add your Instagram handle
youtube: https://www.youtube.com/channel/UCq2MOvUn_W5_Dt_nJtvx9Zw
cv: https://cv.hoangphan.win

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: hoangpm96 # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e